### ISSUE TITLE
Cannot load pre-trained resnet

### ISSUE THREAD

**Issue by Luffy03** [ShenghaiRong/BECO#1]
Thanks for your excellent work! But there are still some bugs in your code. The pre-trained resnet cannot be loaded. And bugs about 'new_data' exist in '_mix_one_withmaskol_bdry' and 'imgmix_one_withmaskol_bdry.

**Comment by ShenghaiRong** [comment]
Thanks for your feedback. Could you provide more details about the errors to help me fix the bugs?

**Comment by Luffy03** [comment]
Missing key(s) in state_dict: "stem_layer.conv1.weight" ......
Should we load a stem-resnet or a normal one? How can I change the setting?

**Comment by ShenghaiRong** [comment]
The bug of loading pre-trained resnet has been fixed, please try again.

**Comment by ShenghaiRong** [comment]
Could you provide more details on bugs about 'new_data' exist in '_mix_one_withmaskol_bdry' and 'imgmix_one_withmaskol_bdry. 
When I run this code, I did not encounter the errors.

**Comment by Luffy03** [comment]
Thanks for your kind answer! It helps me a lot! "*new_data" doesn't work for me. Maybe it is due to my python settings? I fix it like this.
![image](https://user-images.githubusercontent.com/52514670/227867233-25185f5f-b2d7-4cf5-a6f0-7e1955158d23.png)
