### ISSUE TITLE
FileNotFoundError

### ISSUE THREAD

**Issue by geek-APTX4869** [ShenghaiRong/BECO#12]
No such file or directory: './model_weights/resnet50-19c8e357.pth'

**Comment by ShenghaiRong** [comment]
Please refer to https://github.com/jiwoon-ahn/irn/blob/a2ece0034d0a5a9635e4e131cd4fa6e2a779d316/net/resnet50.py#L7

**Comment by geek-APTX4869** [comment]
亲爱的学长：
  如何使用AMN生成伪标签和masks呢，能提供代码让我学习一下吗？
