### ISSUE TITLE
BECO based on DeepLabv2

### ISSUE THREAD

**Issue by JetWings** [ShenghaiRong/BECO#2]
BECO is an exciting work. Could you please provide the ImageNet pretrained model of Deeplabv2 and the implementation code for BECO based on DeepLabv2?

**Comment by ShenghaiRong** [comment]
You can find the implementation for BECO based on DeeplabV2  in the ./configs/deeplabv2_st.json and ./networks/deeplabv2.py. And the link to the ImageNet pre-trained model of DeeplabV2 is provided in README.md. 
To run the BECO-DeeplabV2, you also need to modify the corresponding code in main.py.

**Comment by JetWings** [comment]
Thanks.
