### ISSUE TITLE
Validation on COCO takes too long time?

### ISSUE THREAD

**Issue by chentao2016** [ShenghaiRong/BECO#4]
![image](https://github.com/ShenghaiRong/BECO/assets/24662937/444a48b0-d084-4792-83c6-be29d77bb330)
When running the segmentation network on COCO, training takes 1 hour for each epoch. But the validation will take about 1 day, which means the whole training will take more than one month. Is it normal? Even if  I skip the validation during training, I still think the validation takes too long during testing.

**Comment by ShenghaiRong** [comment]
I've updated the corresponding codes. You can refer to  https://github.com/ShenghaiRong/BECO/blob/3f9c25ac1dc0af23cbebf2d86d5df36413ac2b1f/main.py#L254 and https://github.com/ShenghaiRong/BECO/blob/3f9c25ac1dc0af23cbebf2d86d5df36413ac2b1f/models/train_beco.py#L191C1-L202C62 . You can set "coco_set" as True to skip the validation in the COCO training, and use BECO/test.py to perform the validation manually.

**Comment by chentao2016** [comment]
![image](https://github.com/ShenghaiRong/BECO/assets/24662937/8312142d-d18f-418f-8e76-f8b2bd34bc9f)
Thanks for your quick answer!
I notice that the validation involves a lot of operations like tensorboard and saving the best checkpoint. So do you just select the 40th checkpoint  or select the best checkpoint  for the final result.

**Comment by ShenghaiRong** [comment]
After 35 epochs, the validation results stabilized and converged to about 45.5 mIoU.
