### ISSUE TITLE
Could you provide the code of training with SegFormer?

### ISSUE THREAD

**Issue by Italy2006** [ShenghaiRong/BECO#5]
Thanks for your work, and i want to know how to define the network if i want to train with SegFormer, looking forward to your reply!

**Comment by ShenghaiRong** [comment]
The config and implementation of SegFormer can be found in configs/segformer/segformerb2_st.json and networks/segformer.py. You can refer to the deeplabv3+ in the main.py and modify the code correspondingly.

**Comment by Italy2006** [comment]
> The config and implementation of SegFormer can be found in configs/segformer/segformerb2_st.json and networks/segformer.py. You can refer to the deeplabv3+ in the main.py and modify the code correspondingly.

Thanks for your reply and now i have another question. I follow your work and my network' pseudo label achieves 69.2%mIoU of train label after applying IRN, which outperforms IRN 3.2%, however, the BECO trained by my pseudo label performed worse on valid set than trained by your pseudo label.  Do you have any suggestions about such a phenomenon since it conflicts with your idea in the paper? And i also have tried to adjust the threshold of generating irn_mask but it seems not to work. Looking forward to your reply!

**Comment by Italy2006** [comment]
> The config and implementation of SegFormer can be found in configs/segformer/segformerb2_st.json and networks/segformer.py. You can refer to the deeplabv3+ in the main.py and modify the code correspondingly.

Thanks， but it seems the code didn't provide  'get_backbone' and 'get_decoder' in 'networks/segformer.py'.Can you fix it?

**Comment by ShenghaiRong** [comment]
The bug has been fixed in "networks/segformer.py". And You can refer to the deeplabv3+ in the main.py and the config of segformer_st.json  to complete the "backbone" and "decoder" arguments in segfomer.py.
