### ISSUE TITLE
A question about ‘EdgeDisplacement’

### ISSUE THREAD

**Issue by Italy2006** [ShenghaiRong/BECO#6]
In this network, the image will be padded to the shape of 512x512, it has no problem for VOC2012 since the images of this dataset are smaller than 512x512, howerver, the situation will be different for COCO2014 since some images are larger than 512x512, which will lead the edge predicted by the network is not as large as the cam, could you please fix this bug? Thanks

**Comment by ShenghaiRong** [comment]
Please provide more details!

**Comment by ShenghaiRong** [comment]
The bug has been fixed by commenting on the following line:
https://github.com/ShenghaiRong/BECO/blob/33f44d65ab297d71c762e0842959077261b552ad/first-stage/irn/net/resnet50_irn.py#L226
Please try again.

**Comment by Italy2006** [comment]
> The bug has been fixed by commenting on the following line:
> 
> https://github.com/ShenghaiRong/BECO/blob/33f44d65ab297d71c762e0842959077261b552ad/first-stage/irn/net/resnet50_irn.py#L226
> 
> 
> Please try again.

Thanks for your reply and i notice that when runing the code about COCO， it will generate many images which need to be checked，which means such images all are background， should i make some additional processing?

**Comment by ShenghaiRong** [comment]
Please refer to gen_mask_coco.py:
https://github.com/ShenghaiRong/BECO/blob/33f44d65ab297d71c762e0842959077261b552ad/first-stage/irn/gen_mask_coco.py#L46C1-L63C61
