### ISSUE TITLE
SegmentationClassAug

### ISSUE THREAD

**Issue by liaochuanlin** [ShenghaiRong/BECO#9]
voc.py中SegmentationClassAug文件夹不存在？

**Comment by ShenghaiRong** [comment]
Please refer to [https://blog.csdn.net/lscelory/article/details/98180917](https://blog.csdn.net/lscelory/article/details/98180917). This is the basic setting for VOC training.

**Comment by liaochuanlin** [comment]
Dear author, Hello, this paper is very excellent, but I have a question, what is the role of Mixed labelY,Mixed imageX,Mixed maskM in the article? 
Look forward to your reply!

**Comment by ShenghaiRong** [comment]
In this paper, we propose to boost the prediction of difficult boundary areas.  As a result, we construct some artificial boundaries with accurate labels for different classes of objects. That is to say, only the samples with mixed image, mixed label, and mixed mask can reflect the accurate boundaries, i.e. boundary map B.

**Comment by liaochuanlin** [comment]
In other words, the input of the network is Mixed imageX,Mixed labelY,Mixed imageX,Mixed maskM.

**Comment by ShenghaiRong** [comment]
Please refer to the section 3.4 in the paper and the code in [imgmix.py](https://github.com/ShenghaiRong/BECO/tree/main/datasets/transforms/imgmix.py) for more details.
